# Generated by Django 3.0.3 on 2020-04-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_auto_20200404_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='song',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_name',
        ),
        migrations.AddField(
            model_name='song',
            name='songName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='song_path',
            field=models.FileField(null=True, upload_to='songs/'),
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
