# Generated by Django 3.0.3 on 2020-04-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_auto_20200405_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
