# Generated by Django 3.0.3 on 2020-04-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0004_song_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_name', models.CharField(max_length=50)),
                ('total_songs', models.IntegerField()),
                ('total_albums', models.IntegerField()),
                ('songs', models.ManyToManyField(to='Music.Song')),
            ],
        ),
    ]
