# Generated by Django 3.0.3 on 2020-04-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0005_singer'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='image',
            field=models.FileField(null=True, upload_to='images/singer'),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.FileField(null=True, upload_to='images/song'),
        ),
    ]
