# Generated by Django 3.0.3 on 2020-04-05 16:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Music', '0008_playlists'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Playlists',
            new_name='Playlist',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='user_id',
            new_name='user',
        ),
    ]
