# Generated by Django 3.0.3 on 2020-04-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0010_artist_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='album',
            field=models.ManyToManyField(to='Music.Album'),
        ),
    ]
