# Generated by Django 3.0.3 on 2020-04-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0011_auto_20200414_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='album',
            field=models.ManyToManyField(to='Music.Album'),
        ),
    ]
