# Generated by Django 3.0.3 on 2020-04-26 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0011_singer_album'),
        ('Music', '0012_singer_album'),
    ]

    operations = [
    ]
