# Generated by Django 3.0.3 on 2020-04-26 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0014_auto_20200426_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='id',
            new_name='playlist_id',
        ),
    ]
