# Generated by Django 3.0.3 on 2020-04-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0015_auto_20200426_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='playlist_id',
        ),
        migrations.AddField(
            model_name='playlist',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
